#!/usr/bin/env python
import sys

import navigate_warehouse_via_cli.lib as lib


# pylint: disable=invalid-name
if __name__ == '__main__':
   path = sys.argv[1] if len(sys.argv) == 2 else './graph.pdf'
   flows = lib.generate_schedule(seed=2)
   graph = lib.create_graph(flows)
   lib.draw(graph, path)
