#!/usr/bin/env python
import sys

import navigate_warehouse_via_cli.schedule as schedule


# pylint: disable=invalid-name
if __name__ == '__main__':
    path = sys.argv[1] if len(sys.argv) == 2 else './graph.pdf'
    flows = schedule.generate_schedule(seed=2)
    graph = schedule.create_graph(flows)
    schedule.draw(graph, path)
