#!/usr/bin/env python

import random
import sys

import faker
import lib

import signal

if __name__ == '__main__':
    random.seed(2)
    fake = faker.Faker('en_CA')
    fake.seed(2)

    flows = lib.generate_schedule()

    def handle_sigpipe(signum, frame):
        sys.exit(0)
    signal.signal(signal.SIGPIPE, handle_sigpipe)

    def handle_none(value):
        return value if value else 'NA'

    for flow_name, flow in flows.items():
        for job_name, job in flow.jobs.items():
            for _input in job.inputs:
                print('\t'.join((
                    flow_name,
                    flow.owner,
                    handle_none(flow.frequency),
                    handle_none(flow.slo),
                    job_name,
                    job.resource_class,
                    job.executable,
                    _input,
                    job.output
                )))
