#!/usr/bin/env python

import random

import faker
import lib

if __name__ == '__main__':
    random.seed(2)
    fake = faker.Faker('en_CA')
    fake.seed(2)

    flows = lib.generate_schedule()

    for flow_name, flow in flows.items():
        print(flow_name, flow.owner, flow.frequency, flow.slo)
